customer.insert=INSERT INTO customers (unique_id, name, email) VALUES (?, ?, ?) RETURNING id

customer.find-by-id=SELECT id, unique_id, name, email FROM customers WHERE id = ?

customer.find-by-unique-id=SELECT id, unique_id, name, email FROM customers WHERE unique_id = ?

customer.find-all=SELECT id, unique_id, name, email FROM customers ORDER BY id

customer.exists-by-email=SELECT COUNT(*) FROM customers WHERE email = ?

customer.exists-by-unique-id=SELECT COUNT(*) FROM customers WHERE unique_id = ?

customer.update=UPDATE customers SET unique_id = ?, name = ?, email = ? WHERE id = ?

customer.delete-by-id=DELETE FROM customers WHERE id = ?