payment.insert=INSERT INTO payments (reservation_id, payment_code, method, amount, status, created_at) VALUES (?, ?, ?, ?, ?, ?) RETURNING id

payment.find-by-payment-code=SELECT id, reservation_id, payment_code, method, amount, status, created_at FROM payments WHERE payment_code = ?