INSERT INTO ticket(id,seat,status)
VALUES
(1,1,'AVAILABLE'),
(2,2,'AVAILABLE'),
(3,3,'AVAILABLE'),
(4,4,'AVAILABLE'),
(5,5,'AVAILABLE'),
(6,6,'AVAILABLE'),
(7,7,'AVAILABLE'),
(8,8,'AVAILABLE'),
(9,9,'AVAILABLE'),
(10,10,'AVAILABLE');