spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ticket-reservation
  mongodb:
    uri: ${MONGODB_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  cloud:
    gcp:
      project-id: ${PUBSUB_PROJECT_ID}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

reservation:
  expiration: ${RESERVATION_EXPIRATION:PT30M}

server:
  port: ${SERVER_PORT:8080}

pubsub:
  project-id: ${PUBSUB_PROJECT_ID}
  topic-id: ${PUBSUB_TOPIC_ID}
  #subscription: ${PUBSUB_SUBSCRIPTION_ID:passenger-checked-in-subscription}

logging:
  level:
    org.example.ticketreservation: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.core: DEBUG