spring:
  application:
    name: ticket-reservation

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticket_reservation}
    username: ${DB_USERNAME:ticket_user}
    password: ${DB_PASSWORD:ticket_password}
    driver-class-name: org.postgresql.Driver

    sql:
      init:
        mode: always
        schema-locations: classpath:db/schema.sql

    threads:
      virtual:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

reservation:
  expiration: ${RESERVATION_EXPIRATION:PT30M}

server:
  port: ${SERVER_PORT:8080}