services:

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ticket_reservation
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_password
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"

  pubsub:
    image: google/cloud-sdk:latest
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --project=ticket-reservation-local
      - --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"