-- =========================================================
-- TICKET RESERVATION SYSTEM
-- PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- 1. CUSTOMERS
-- =========================================================

CREATE TABLE IF NOT EXISTS customers (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                         unique_id VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,

    CONSTRAINT uk_customers_unique_id UNIQUE (unique_id),
    CONSTRAINT uk_customers_email UNIQUE (email)
    );


-- =========================================================
-- 2. TRANSPORTS
-- =========================================================

CREATE TABLE IF NOT EXISTS transports (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                          code VARCHAR(50) NOT NULL,
    company VARCHAR(150) NOT NULL,
    plate VARCHAR(30) NOT NULL,

    CONSTRAINT uk_transports_code UNIQUE (code),
    CONSTRAINT uk_transports_plate UNIQUE (plate)
    );


-- =========================================================
-- 3. TRIPS
-- =========================================================

CREATE TABLE IF NOT EXISTS trips (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     origin VARCHAR(150) NOT NULL,
    destination VARCHAR(150) NOT NULL,
    transport_id BIGINT NOT NULL,
    departure_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_trips_transport
    FOREIGN KEY (transport_id)
    REFERENCES transports(id)
    );


-- =========================================================
-- 4. SEATS
-- =========================================================

CREATE TABLE IF NOT EXISTS seats (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     trip_id BIGINT NOT NULL,
                                     seat_number VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_seats_trip
    FOREIGN KEY (trip_id)
    REFERENCES trips(id),

    CONSTRAINT uk_seats_trip_number
    UNIQUE (trip_id, seat_number),

    CONSTRAINT chk_seats_status
    CHECK (
              status IN (
              'AVAILABLE',
              'RESERVED',
              'SOLD'
                        )
    )
    );


-- =========================================================
-- 5. RESERVATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS reservations (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                            reservation_code VARCHAR(50) NOT NULL,
    payment_code VARCHAR(10) NOT NULL,

    customer_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,

    status VARCHAR(30) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uk_reservations_code
    UNIQUE (reservation_code),

    CONSTRAINT uk_reservations_payment_code
    UNIQUE (payment_code),

    CONSTRAINT fk_reservations_customer
    FOREIGN KEY (customer_id)
    REFERENCES customers(id),

    CONSTRAINT fk_reservations_trip
    FOREIGN KEY (trip_id)
    REFERENCES trips(id),

    CONSTRAINT fk_reservations_seat
    FOREIGN KEY (seat_id)
    REFERENCES seats(id),

    CONSTRAINT chk_reservations_status
    CHECK (
              status IN (
              'PENDING_PAYMENT',
              'CONFIRMED',
              'CANCELLED',
              'EXPIRED'
                        )
    ),

    CONSTRAINT chk_reservations_expiration
    CHECK (expires_at >= created_at)
    );


-- =========================================================
-- 6. PAYMENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS payments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                        reservation_id BIGINT NOT NULL,
                                        payment_code VARCHAR(10) NOT NULL,

    method VARCHAR(30) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_payments_reservation
    FOREIGN KEY (reservation_id)
    REFERENCES reservations(id),

    CONSTRAINT uk_payments_payment_code
    UNIQUE (payment_code),

    CONSTRAINT uk_payments_reservation
    UNIQUE (reservation_id),

    CONSTRAINT chk_payments_method
    CHECK (
              method IN (
              'TRANSFERENCIA',
              'MOVIL',
              'OTROS'
                        )
    ),

    CONSTRAINT chk_payments_status
    CHECK (
              status IN (
              'PENDING',
              'PAID',
              'REJECTED'
                        )
    ),

    CONSTRAINT chk_payments_amount
    CHECK (amount > 0)
    );


-- =========================================================
-- 7. TICKETS
-- =========================================================

CREATE TABLE IF NOT EXISTS tickets (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                       ticket_code VARCHAR(50) NOT NULL,
    reservation_id BIGINT NOT NULL,

    issued_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uk_tickets_code
    UNIQUE (ticket_code),

    CONSTRAINT uk_tickets_reservation
    UNIQUE (reservation_id),

    CONSTRAINT fk_tickets_reservation
    FOREIGN KEY (reservation_id)
    REFERENCES reservations(id)
    );


-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_reservations_status
    ON reservations(status);


CREATE INDEX IF NOT EXISTS idx_reservations_expires_at
    ON reservations(expires_at);


CREATE INDEX IF NOT EXISTS idx_reservations_status_expires_at
    ON reservations(status, expires_at);


CREATE INDEX IF NOT EXISTS idx_reservations_customer
    ON reservations(customer_id);


CREATE INDEX IF NOT EXISTS idx_reservations_trip
    ON reservations(trip_id);


CREATE INDEX IF NOT EXISTS idx_seats_trip
    ON seats(trip_id);